### ISSUE TITLE
Unable to deploy smart contract using aurora engine

### ISSUE THREAD

**Issue by puneet166** [aurora-is-near/aurora-engine#276]
@artob @joshuajbouw @birchmd @mrLSD. please help. We did a setup of localnet near's validator node followed this link ``` https://docs.near.org/docs/develop/node/validator/compile-and-run-a-node#localnet ```

After completed all instructors. our validator node has started locally. but issue which we are facing right now that is - 
When we are running this command ``` aurora install --chain 1313161556 --owner test.near betanet-release.wasm ``` 
The error is ocuurring -
``` Receipt: 7HRBmSGbyPs4tfg2T9hqmrAzoLB1wR5HS19kg6nW4qGB
        Failure [aurora.test.near]: Error: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: assertion failed: `(left == right)`\n  left: `[116, 101, 115, 116, 46, 110, 101, 97, 114]`,\n right: `[97, 117, 114, 111, 114, 97, 46, 116, 101, 115, 116, 46, 110, 101, 97, 114]`: ERR_PRIVATE_CALL [src/sdk.rs:555:5]"}}
/usr/local/lib/node_modules/@aurora-is-near/cli/node_modules/@hqoss/monads/dist/lib/result/result.js:70
            throw new ReferenceError("Cannot unwrap Ok value of Result.Err");
                  ^

ReferenceError: Cannot unwrap Ok value of Result.Err
    at Object.unwrap (/usr/local/lib/node_modules/@aurora-is-near/cli/node_modules/@hqoss/monads/dist/lib/result/result.js:70:19)
    at Command.<anonymous> (file:///usr/local/lib/node_modules/@aurora-is-near/cli/lib/aurora.js:30:66)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```
What we have done so far in aurora-engine-

We followed these below instructions-
1. Cloned master branch

2. We ran these commands for Rust nightly and GNU Make 
```
rustup install nightly-2021-03-25
rustup target add wasm32-unknown-unknown --toolchain nightly-2021-03-25
```
3. Ran ``` make -B betanet ```

4.  Installed the Aurora CLI tool using ``` npm install -g aurora-is-near/aurora-cli ```
5.  When we are running these commands 
```
export NEAR_ENV=local
near delete aurora.test.near test.near  # if needed
near create-account aurora.test.near --master-account=test.near --initial-balance 1000000
aurora install --chain 1313161556 --owner test.near betanet-release.wasm
```
The above error coming while we are running this ``` aurora install --chain 1313161556 --owner test.near betanet-release.wasm ``` .

npm version which we are using is  ``` 6.14.8 ```
node version which we are using is  ``` 14.15.1 ```

**Comment by birchmd** [comment]
Hi @puneet166 

Thanks for filing this issue! I am not able to reproduce it, but maybe we can figure out why it is not working for you.

It looks like you are trying to install `aurora` on a sub-account, so you may need to specify that in the `install` command. Can you try the following command?

```
aurora --signer aurora.test.near --engine aurora.test.near  install --chain 1313161556 --owner test.near betanet-release.wasm
```

This worked for me locally.

I was also using [the `aurora-cli` directly from the repository](https://github.com/aurora-is-near/aurora-cli/blob/master/lib/aurora.js) as opposed to the package from npm. So if you are still having trouble then you could try that instead; it might be the npm package is out of date.

Let me know if it still is not working for you.

**Comment by puneetsingh166** [comment]
Hi @birchmd Thanks for your response. Which version of npm and node were you using when installing aurora cli or run this command  ``` aurora --signer aurora.test.near --engine aurora.test.near  install --chain 1313161556 --owner test.near betanet-release.wasm ```

**Comment by birchmd** [comment]
@puneet166 

npm version: `7.21.1`
node version: `v16.9.0`

**Comment by puneetsingh166** [comment]
@birchmd  when installing aurora CLI using this command ``` npm install -g aurora-is-near/aurora-cli ``` 
getting these below errors - 
```
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/README.md'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/account.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/block.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/config.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/engine.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/index.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/key_store.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/prelude.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/schema.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/transaction.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/node_modules/@aurora-is-near/engine/lib/utils.d.ts'
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/lib/aurora.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pp/.nvm/versions/node/v16.9.0/lib/node_modules/@aurora-is-near/cli/lib/aurora.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pp/.npm/_logs/2021-09-21T05_39_26_980Z-debug.log
```
Os - ``` ubuntu 20.04 ```
npm version ``` 7.21.1 ``` 
node version ``` 16.9.0 ```

**Comment by birchmd** [comment]
That will be fixed in https://github.com/aurora-is-near/aurora-cli/issues/13

In the meantime you can clone the CLI repo and use the JS script directly

```
git clone https://github.com/aurora-is-near/aurora-cli.git
cd aurora-cli
npm install
./lib/aurora.js --help
```
