### ISSUE TITLE
aurora initialize with KeyNotFound issue

### ISSUE THREAD

**Issue by minliacom** [aurora-is-near/aurora-engine#404]
I follow the doc from home page, but got error KeyNotFound.

```
near deploy --account-id=aurora.test.near --wasm-file=mainnet-release.wasm
Loaded master account test.near key from /Users/user/.neartosis/2021-12-18T15.04.13/validator-key.json with public key = ed25519:3nkVdWWuTA6cRHp2rAbjuc3aUF8M4E6brNidoe8q14He
Starting deployment. Account id: aurora.test.near, node: http://127.0.0.1:58138, helper: http://127.0.0.1:58344, file: mainnet-release.wasm
Transaction Id 2umeuYMtM3W3T8jVCYkorMqc3AHFwopJtDTcpY7auCQn
To see the transaction in the transaction explorer, please open this url in your browser
http://127.0.0.1:59141/transactions/2umeuYMtM3W3T8jVCYkorMqc3AHFwopJtDTcpY7auCQn
Done deploying to aurora.test.near



aurora initialize --chain 1313161556 --owner test.near
TypedError: Can not sign transactions for account test.near on network local, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryKeyStore, InMemoryKeyStore, UnencryptedFileSystemKeyStore(/Users/user/.near-credentials))).
    at Account.signTransaction (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/near-api-js/lib/account.js:74:19)
    at async /Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/near-api-js/lib/account.js:91:34
    at async Object.exponentialBackoff [as default] (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransaction (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/near-api-js/lib/account.js:90:24)
    at async Engine.callMutativeFunction (file:///Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/@aurora-is-near/engine/lib/engine.js:312:28)
    at async Engine.promiseAndThen (file:///Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/@aurora-is-near/engine/lib/engine.js:85:19)
    at async Engine.initialize (file:///Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/node_modules/@aurora-is-near/engine/lib/engine.js:80:20)
    at async Command.<anonymous> (file:///Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/@auroraisnear/cli/lib/aurora.js:44:32) {
  type: 'KeyNotFound',
  context: undefined
}

```

So,  where can I find the credential file?

Thanks.

**Comment by joshuajbouw** [comment]
Missing key in `/Users/user/.near-credentials`.

See: https://docs.near.org/docs/concepts/account#how-to-create-a-dev-account

**Comment by minliacom** [comment]
So cool. thank you so much.
